config/routes.rb
Rails.application.routes.draw do
  root to: "gossips#index" #donne l'info sur où se trouve la racine
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  #get 'author/:id', to: 'users#show', as: 'user'

  resources :gossips #va générer toutes les routes Gossip en auto
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips

  validates :title, 
    presence: true, 
    length: { in: 3..70 }
  validates :content, presence: true
end

app/models/join_private_message_receiver.rb
class JoinPrivateMessageReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :receiver, class_name: "User"
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"  
  has_many :join_private_message_receivers
  has_many :receivers, class_name: "User", through: :join_private_message_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, class_name: "JoinPrivateMessageReceiver", foreign_key: 'receiver_id'

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  
  has_secure_password

  #so User cannot be added if password none or too short
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = @city.users
    @gossips = Gossip.joins(:user).where(users: {city_id: @city.id})
  end

  #pour ce qui est de la création de ville, comme elle se fait via le formulaire User, ce n'est pas ici que l'on voit le code
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  def index
    @gossips = Gossip.all
  end
  
  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end
  
  def create #treate infos and save into DB
    
    @gossip = Gossip.create(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' => current_user.id)

    #mettre le lien avec helper à vérifier
    #@gossip.new = @gossip.current_user

    if @gossip.save
      flash[:success] = "Thanks for your Gossip XOXO"
      redirect_to "/"
    else
      @gossip.errors.full_messages.each do |message|
        flash[:error] = message
      end
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id]) #cf find_by de Sam
  end
  
  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params) #rechercher dans vidéo ceux à quoi correspond post_params ou sinon copier ligne 16 à 19
    redirect_to "/"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to "/"
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #correspond à la page de login
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/", notice: "Connexion Success"

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy #correspond au logout
    session.delete(:user_id) #pas d'arobase car pas un objet
    redirect_to "/"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    city_name = params[:city_name]
    zip_code = params[:zip_code]

    city = City.find_by(name: city_name, zip_code: zip_code)

    if city #si déjà dans ma BDD
      city_id = city.id
    else
      new_city = City.create(name: city_name, zip_code: zip_code)
      city_id = new_city.id 
    end

    @user = User.create(
      'first_name' => params[:first_name],
      'last_name' => params[:last_name],
      'description' => params[:description],
      'email' => params[:email],
      'age' => params[:age],
      'city_id' => city_id,
      'password' => params[:password])

    if @user.save
      flash[:success] = "Welcome!"
      redirect_to "/"
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:gossip).permit(:first_name, :last_name, :email, :password_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/show.html.erb
<div class="px-4 pt-5 pb-2 my-5 text-center">
  <h1 class="display-5 fw-bold"><em><%= @city.name %></em></h1>
  <br>
  <div class="col-lg-6 mx-auto">
    <p class="text-secondary font-italic">Have you evere heard 'What's going on in Vegas, stay in Vegas?', this is the same here... So enjoy Gossip from <%= @city.name %>, but keep them for yourself!</p>
  </div>
</div>

<div class="row px-4 py-2">
  <% @gossips.each do |gossip|%> 
    <div class="col-sm-4 my-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Author: <%= gossip.user.first_name %></p>
          <div class="row">
            <div class="text-end">
              <%= link_to "See More", gossip_path(gossip), class:"btn btn-pink me-2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/edit.html.erb
<div class="px-4 py-5 mb-5 text-center">
  <h6 class="display-6 fw-bold"><em>Share Your Gossip XOXO</em></h6>
  <br>

  <div class="col-lg-6 mx-auto">

    <%= form_for @gossip do |f| %>
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

      <div class="form-floating mb-3">
        <h4><%= f.label 'floatingTitle', 'Title' %></h4>
        <p><small class="text-muted"><em>Your title should be between 3 and 70 characters</em></small></p>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <br />

      <div class="form-floating mb-3">
        <h4><%= f.label 'floatingTitle', 'Your Gossip Content' %></h4>
        <p><small class="text-muted"><em>Shhhhh... We won't tell</em></small></p>
        <%= f.text_area :content, class: "form-control" %>
      </div>

      <br />
      
      <div class="form-floating mb-3">
        <%= f.submit "Gossip update", class: "btn btn-full-pink"  %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/gossips/index.html.erb
<div class="hero-color px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold"><em>Last Gossip</em></h1>
  <div class="col-lg-6 mx-auto">
    <blockquote class="blockquote lead mb-4">
      <br>
      <p><%= @gossips.last.content %></p>
      <br>
      <div class="blockquote-footer txt-white"><%= @gossips.last.user.first_name %> <%= @gossips.last.user.last_name %></div>
    </blockquote>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <% if current_user%>
        <%= link_to "Share a Gossip", new_gossip_path, class:"btn btn_white px-4 gap-3"%>
      <%else%>
        <%= link_to "Connect to Share a Gossip!", root_path, class:"btn btn_white px-4 gap-3"%>
      <%end%>
      
    </div>
  </div>
</div>

<div class="row px-4 py-2">
  <% @gossips.each do |gossip|%> 
    <div class="col-sm-4 my-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text">Author: <%= gossip.user.first_name %></p>
          <div class="row">
            <div class="text-end">
              <%= link_to "See More", gossip_path(gossip.id), class:"btn btn-pink me-2" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h6 class="display-6 fw-bold"><em>Share Your Gossip XOXO</em></h6>
  <br>

  <div class="col-lg-6 mx-auto">

    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

      <div class="form-floating mb-3">
        <h4><%= label_tag 'floatingTitle', 'Title' %></h4>
        <p><small class="text-muted"><em>Your title should be between 3 and 25 characters</em></small></p>
        <%= text_field_tag 'title', @gossip.title, class: "form-control", id: "floatingTitle", placeholder: "Your Title", required: true %>
        <div class="invalid-feedback">
          Please enter a title (between 3 and 25 characters).
        </div>
      </div>

      <br />

      <div class="form-floating mb-3">
        <h4><%= label_tag 'floatingTitle', 'Your Gossip Content' %></h4>
        <p><small class="text-muted"><em>Shhhhh... We won't tell</em></small></p>
        <%= text_area_tag 'content', @gossip.content, class: "form-control", id: "floatingContent", placeholder: "Your Gossip Content", required: true %>
        <div class="invalid-feedback">
          Please enter your gossip content.
        </div>
      </div>

      <br />
      
      <div class="form-floating mb-3">
        <%= submit_tag "Send your Gossip...", class: "btn btn-full-pink"  %>
      </div>
    <% end %>
    
  </div>
</div>
    

app/views/gossips/show.html.erb
<div class="px-4 py-5 my-5 justify-content-center">
  <div class="row justify-content-center">
    <div class="col-sm-4 my-4">
      <div class="card gossip_card_border">
        <div class="card-body">
          <h5 class="card-title"><%= @gossip.title %></h5>
          <br>
          <p class="card-text">Content:</p>
          <p class="card-text"><%= @gossip.content %></p>
          <div>Author: <%= link_to @gossip.user.first_name, user_path(@gossip.user.id), class:"card-text"%></div>
          <div>City: <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id), class:"card-text"%></div>
          
          <p class="card-text"><small class="text-muted">Created at: <%= @gossip.created_at %></small></p>
          
          <% if current_user == @gossip.user%>
            <div class="d-flex align-items">
              <%= link_to "Update", edit_gossip_path, class:"btn btn-pink me-3" %>
              <%= button_to "Obliviate", gossip_path, method: :delete, class:"btn btn-pink me-2" %>
            </div>
          <%end%>
          
        </div>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>

<div class="px-4 py-4 my-5 text-center">
  <p>Find me in app/views/static_pages/contact.html.erb</p>
</div>

app/views/static_pages/team.html.erb
<head>
  <title>Team</title>
</head>

<body>
  <div class="px-4 py-4 my-5 text-center">
    <%= image_tag("gossip_team.png", class: "text-center", alt: "Gossip Team", style: "max-width: 1100px;")%>
  </div>
</body>

app/views/users/new.html.erb
<div class="px-4 py-5 my-5 text-start">
  <h4 class="display-6 fw-bold text-center"><em>Create your Account</em></h4>
  <br>

  <div class="col-lg-6 mx-auto">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      
      <%= label_tag "What's your first name?" %>
      <%= text_field_tag 'first_name', @user.first_name, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Please enter a first name.
      </div>

      <br />

      <%= label_tag "What's your last name?" %>
      <%= text_field_tag 'last_name', @user.last_name, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Please enter a last name.
      </div>
      
      <br />
      
      <%= label_tag "Give us few words about you" %>
      <%= text_field_tag 'description', @user.description, class: "form-control"%>
      
      <br /> 

      <%= label_tag "What's your email?" %>
      <%= text_field_tag 'email', @user.email, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Please enter a valid email.
      </div>
      
      <br />
      
      <%= label_tag "Give me your age... Shhh I won't tell" %>
      <%= text_field_tag 'age', @user.age, class: "form-control"%>
      
      <br />

      <%= label_tag "Where do you live?" %>
      <%= text_field_tag 'city_name', nil, class: "form-control", required: true %>

      <br />

      <%= label_tag "Enter your Zip Code" %>
      <%= text_field_tag 'zip_code', nil, class: "form-control", required: true%>
      
      <br />

      <%= label_tag "Last step, define a password" %>
      <%= text_field_tag 'password', @user.password, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Please enter a valid password (at least 6 characters).
      </div>

      <br />
      <br />
      <div class="text-center">
        <%= submit_tag "Create my profil", class: "btn btn-full-pink"  %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row px-4 py-2 my-5 justify-content-center">
  <div class="col-sm-4 my-4">
    <div class="card gossip_card_border">
      <div class="card-body">
        <h5 class="card-title"><%= @user.first_name %></h5>
        <br>
        <p class="card-text">Last Name: <%= @user.last_name %></p>
        <p class="card-text">Description: <%= @user.description %></p>
        <p class="card-text">Email: <%= @user.email %></p>
        <p class="card-text">Age: <%= @user.age %> years old</p>
        <p class="card-text">City: <%= link_to @user.city.name, city_path(@user.city.id) %></p>
      </div>
    </div>
  </div>
</div>