config/routes.rb
Rails.application.routes.draw do
  root to: "gossips#index" #donne l'info sur où se trouve la racine
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  #get 'author/:id', to: 'users#show', as: 'user'

  resources :gossips #va générer toutes les routes Gossip en auto
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips

  validates :title, 
    presence: true, 
    length: { in: 3..70 }
  validates :content, presence: true
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"  
  has_many :join_private_message_receivers
  has_many :receivers, class_name: "User", through: :join_private_message_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, class_name: "JoinPrivateMessageReceiver", foreign_key: 'receiver_id'

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  
  has_secure_password

  #so User cannot be added if password none or too short
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = @city.users
    @gossips = Gossip.joins(:user).where(users: {city_id: @city.id})
  end

  #pour ce qui est de la création de ville, comme elle se fait via le formulaire User, ce n'est pas ici que l'on voit le code
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  def index
    @gossips = Gossip.all
  end
  
  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end
  
  def create #treate infos and save into DB
    
    @gossip = Gossip.create(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' => current_user.id)

    #mettre le lien avec helper à vérifier
    #@gossip.new = @gossip.current_user

    if @gossip.save
      flash[:success] = "Thanks for your Gossip XOXO"
      redirect_to "/"
    else
      @gossip.errors.full_messages.each do |message|
        flash[:error] = message
      end
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id]) #cf find_by de Sam
  end
  
  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params) #rechercher dans vidéo ceux à quoi correspond post_params ou sinon copier ligne 16 à 19
    redirect_to "/"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to "/"
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #correspond à la page de login
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/", notice: "Connexion Success"

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy #correspond au logout
    session.delete(:user_id) #pas d'arobase car pas un objet
    redirect_to "/"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def team
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    city_name = params[:city_name]
    zip_code = params[:zip_code]

    city = City.find_by(name: city_name, zip_code: zip_code)

    if city #si déjà dans ma BDD
      city_id = city.id
    else
      new_city = City.create(name: city_name, zip_code: zip_code)
      city_id = new_city.id 
    end

    @user = User.create(
      'first_name' => params[:first_name],
      'last_name' => params[:last_name],
      'description' => params[:description],
      'email' => params[:email],
      'age' => params[:age],
      'city_id' => city_id,
      'password' => params[:password])

    if @user.save
      flash[:success] = "Welcome!"
      redirect_to "/"
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:gossip).permit(:first_name, :last_name, :email, :password_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-sm-6 col-md-4">
      <%= link_to "The Gossip Project", root_path, class:"linkfooter d-block py-lg-3 py-md-3"%>
    </div>
    <div class="col-sm-6 col-md-4">
      <%= link_to "The Hacking Project", "https://www.thehackingproject.org", class:"linkfooter d-block py-lg-3 py-md-3"%>
    </div>
    <div class="col-sm-6 col-md-4">
      <%= link_to "BackEnd Access", "https://github.com/Blanchard-Floriane/Fullstack_W03_D03_Gossip_Project_Full_CRUD", class:"linkfooter d-block py-lg-3 py-md-3"%>
    </div>
  </div>
</div>
  

app/views/layouts/_navbar.html.erb
<!--Header contain only my navbar-->
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    <%= link_to "The Gossip Project", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <% if current_user%>
            <%= link_to "New Gossip", new_gossip_path, class:"nav-link"%>
          <%else%>
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to "Team", team_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">My Session</a>
        <ul class="dropdown-menu">
          <% if current_user%> 
            <li><%= button_to "Deconnexion", session_path(current_user.id), method: :delete, class:"dropdown-item"%></li>
          <%else%>
            <li><%= link_to "Sign Up", new_user_path, class:"dropdown-item"%></li>
            <li><%= link_to "Log in", new_session_path, class:"dropdown-item"%></li>
          <%end%>
        </ul>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Bootstrap -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8f02447683.js" crossorigin="anonymous"></script>
    
    <!-- CSS personnalisé pas besoin de code car l'app sait où cheercher le css -->

    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body data-turbo="false">

    <header class="nav-custom fw-light lh-base">
      <%= render 'layouts/navbar' %> <!-- Inclure la barre de navigation ici -->
    </header>

    <!-- Code HTML pour afficher les messages flash -->
    <div class="custom-alerts">
      <% if flash[:success].present? %>
        <div class="alert alert-success custom_alert" role="alert">
          <%= flash[:success] %>
        </div>
      <% elsif flash[:alert].present? %>
        <div class="alert alert-danger custom_alert" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    
    <!--Yield is all my page content-->
    <%= yield %>

    <!-- footer général -->
    <footer class="custom-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>